### ISSUE TITLE
Need to sync with AUR

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-eigen-stl-containers#6]
This package is currently preventing `ros-melodic-moveit-core` from building.
A fellow ROS Arch user is having trouble with the above package. https://aur.archlinux.org/packages/ros-melodic-moveit-core/#comment-699444

Let's help him out!

All that needs to happen is a sync for this package. The master branch PKGBUILD installs fine on my system.

**Comment by acxz** [comment]
@bionade24 Can we get a status on the CI? Or can you sync this to the AUR?

I really want to get rid of the sync to AUR and need to sync issues, particularly because moveit is a big library for ROS and it does not build for ArchLinux.

**Comment by bionade24** [comment]
moveit fails because of some python 2 packages. I.didn't have the time to fix it yet.

**Comment by acxz** [comment]
@bionade24 Can you give more details, I can try fixing those python2 packages.

**Comment by acxz** [comment]
synced to AUR
